Групповой спринт
Bolohonov/java-filmorate pull request #23
Opened 2022-06-10 08:13 UTC by Bolohonov

2022-06-11 07:10 UTC, Bolohonov commented
Что-то не так, ревьюер не видит некоторые классы

2022-06-12 16:33 UTC, eugene-lenkevich requested changes
Привет,  Михаил, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста

И еще моментик, а получится ли добавить в описание PR то что было сделано в рамках конкретной доработки, вижу есть сообщения в комитах, но хочется еще какое-то более высокоуровневое описание?

2022-06-12 16:33 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/EventController.java
> +    public EventController(EventService eventService) {
А не получится воспользоваться @RequiredArgsConstructor?
Лучше все делать единообразно :)

2022-06-12 16:33 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        log.warn("Search films");
А почему warn, все же вроде по плану идет :)
И еще б query залогировать, например с уровнем debug (хотя можно и info)

2022-06-12 16:33 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/GenreNotFoundException.java
> +public class GenreNotFoundException extends RuntimeException {
А подходит ли для данной ситуации непроверяемое исключение?
Какой то жанр не найден - вполне себе штатная ситуация, пусть тут будет проверяемое исключение :)
extends Exception

Аналогично про исключения ниже, надо ли их делать непроверяемыми?

2022-06-12 16:33 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +    @NotNull
Что то мне подсказывает что @NotBlank включает в себя @NotNull :)

2022-06-14 17:45 UTC, eugene-lenkevich approved these changes
Список изменений конечно обстоятельный :)

А так, все супер, спасибо!

2022-06-14 19:21 UTC, merged