feat:Add sprint_8 homework
Bolohonov/java-filmorate pull request #5
Opened 2022-04-18 19:45 UTC by Bolohonov

2022-04-18 19:49 UTC, Bolohonov commented
Я изменил в тестах для user и film "creat Fail" код ответа c 500 на 400 , т.к. использовал аннотацию springboot validation @Email для проверки email адреса, а он при неверном запросе возвращает код ошибки BAD REQUEST

2022-04-19 16:22 UTC, kukolev requested changes

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private static final Map<Integer, Film> films = new HashMap<>();
Статическое поле это плохое решение. Дело в том, что теперь у нескольких экземпляров класса будет общий список фильмов, что может привести к ошибке. В данном случае это не критично, т.к. FilmController это бин спринга, но вообще лучше поправить.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private static final Map<Integer, User> users = new HashMap<>();
Статическое поле это плохое решение. Дело в том, что теперь у нескольких экземпляров класса будет общий список фильмов, что может привести к ошибке. В данном случае это не критично, т.к. UserController это бин спринга, но вообще лучше поправить.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private static boolean validation(User user) {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. 

Нужно поправить здесь и в методах ниже.

2022-04-19 16:22 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-19 16:22 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    FilmController controller = new FilmController();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-19 16:22 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    UserController controller = new UserController();
Нарушен принцип инкапсуляции. Поля класса не должны быть видимы другим классам. Лучше сделать поле приватным и сделать геттер и сеттер для полей, если нужен доступ извне.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            film.setId(1);
Так делать не следует. Метода валидации должен проверять фильм и возвращать false, если проверка не пройдена. Присваивать другой id или делать еще что-то должен внешний код. Ведь на этом уровне мы не можем знать, как обработать ситуацию. Если присваивать всем некорректным фильмам один и тот-же айдишник = 1, то можно спровоцировать ошибки в логике работы.

Аналогичные проблемы есть и в других методах

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            user.setName(user.getLogin());
Здесь и ниже такая же проблема, как и в FilmController - валидация не должна приводить к изменению сущности.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        } catch (NullPointerException exp) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-04-19 16:22 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        } catch (NullPointerException exp) {
Перехватывать NullPointerException плохая практика. Дело в том, что всегда можно найти место в коде, которое является причиной этой ошибки и проверить на null.

2022-04-21 15:34 UTC, merged